### Créer un site
POST http://127.0.0.1:8000/site/
Content-Type: application/json

{
  "nom": "Site Central",
  "adresse": "10 rue de la Paix, 75000 Paris",
  "horaires_ouverture": "08:30:00",
  "horaires_fermeture": "18:00:00"
}

### Lire tous les sites
GET http://127.0.0.1:8000/site/
Accept: application/json

### Supprimer un site
DELETE http://127.0.0.1:8000/site/3
Accept: application/json