

@baseUrl = http://127.0.0.1:8000

### Listing simple (par défaut)
GET {{baseUrl}}/ressources

### Pagination (offset/limit)
GET {{baseUrl}}/ressources?offset=0&limit=10

### Filtre par type (salle | equipement | vehicule)
GET {{baseUrl}}/ressources?type_of_ressource=salle

### Filtre par site
GET {{baseUrl}}/ressources?site_id=1

### Filtre par localisation (ville contient)
GET {{baseUrl}}/ressources?ville=Paris

### Filtre par code postal
GET {{baseUrl}}/ressources?code_postal=75001

### Disponibilité générale
GET {{baseUrl}}/ressources?disponible=true

### disponible=false -> etat != active
GET {{baseUrl}}/ressources?disponible=false

### Filtre par caractéristiques (CSV)
GET {{baseUrl}}/ressources?caracteristiques=projecteur

### Capacité minimale (utile pour les salles)
GET {{baseUrl}}/ressources?type_of_ressource=salle&minimum_capacity=10

### Tri par nom (asc/desc)
GET {{baseUrl}}/ressources?sort_by=nom&sort_order=asc

### Tri par capacité
GET {{baseUrl}}/ressources?sort_by=capacite&sort_order=desc

### Tri par type
GET {{baseUrl}}/ressources?sort_by=type&sort_order=asc

### Combo: type + site + ville + dispo + caracs + capacité + pagination + tri
GET {{baseUrl}}/ressources?type_of_ressource=salle&site_id=1&disponible=true&caracteristiques=projecteur&minimum_capacity=8&offset=0&limit=5&sort_by=capacite&sort_order=desc

### Créer une ressource (exemple salle)
POST {{baseUrl}}/ressources
Content-Type: application/json

{
  "nom": "Salle A100",
  "type_ressource": "salle",
  "capacite_maximum": 12,
  "description": "Salle de réunion",
  "caracteristiques": ["projecteur", "tableau"],
  "site_id": 1,
  "etat": "active",
  "horaires_ouverture": "08:00:00",
  "horaires_fermeture": "18:00:00",
  "images": [],
  "tarifs_horaires": 25.0
}

### Récupérer une ressource par id
GET {{baseUrl}}/ressources/2

###  Supprimer une ressource
DELETE {{baseUrl}}/ressources/1

### modifier une ressource
PUT {{baseUrl}}/ressources/2
Content-Type: application/json

{
  "tarifs_horaires": 30,
  "horaires_fermeture": "16:30:00"
}